using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("ThoughtWorks Inc.")]
[assembly: AssemblyProductAttribute("CruiseControl.NET")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2003 - 2024 ThoughtWorks Inc.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.9.0.0")]
[assembly: AssemblyFileVersionAttribute("1.9.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.9.0+3849.Branch.master.Sha.bcb43c3c1992c41f6a0cc4564b520b5e2b2af973")]

